/**
 * compress-images.mjs
 *
 * Compresses all clinic photos from public/assets/hassan-pt/photos/
 * into public/assets/hassan-pt/photos-compressed/ using sharp.
 *
 * Targets: JPEG ~400kb max, WebP fallback generated by Next.js at runtime.
 *
 * Usage:
 *   npm install --save-dev sharp
 *   node scripts/compress-images.mjs
 *
 * Output folder is what you upload to DO Spaces.
 */

import sharp from 'sharp';
import { readdir, mkdir } from 'fs/promises';
import { existsSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT      = path.join(__dirname, '..');

const INPUT_BASE  = path.join(ROOT, 'public', 'assets', 'hassan-pt', 'photos');
const OUTPUT_BASE = path.join(ROOT, 'public', 'assets', 'hassan-pt', 'photos-compressed');

const JPEG_QUALITY = 82;   // 80–85 is visually lossless for clinic photos
const MAX_WIDTH    = 1600; // cap width — retina 800px display width

let total = 0;
let saved = 0;

async function processDir(inputDir, outputDir) {
  if (!existsSync(outputDir)) {
    await mkdir(outputDir, { recursive: true });
  }

  const entries = await readdir(inputDir, { withFileTypes: true });

  for (const entry of entries) {
    const inputPath  = path.join(inputDir, entry.name);
    const outputPath = path.join(outputDir, entry.name);

    if (entry.isDirectory()) {
      await processDir(inputPath, outputPath);
      continue;
    }

    const ext = path.extname(entry.name).toLowerCase();
    if (!['.jpg', '.jpeg', '.png'].includes(ext)) continue;

    try {
      const image = sharp(inputPath);
      const meta  = await image.metadata();

      const inputSizeKB = (await import('fs')).statSync(inputPath).size / 1024;

      await image
        .resize({ width: Math.min(meta.width ?? MAX_WIDTH, MAX_WIDTH), withoutEnlargement: true })
        .jpeg({ quality: JPEG_QUALITY, progressive: true, mozjpeg: true })
        .toFile(outputPath.replace(/\.(png|jpeg)$/i, '.jpg'));

      const outputSizeKB = (await import('fs')).statSync(
        outputPath.replace(/\.(png|jpeg)$/i, '.jpg')
      ).size / 1024;

      const reduction = Math.round((1 - outputSizeKB / inputSizeKB) * 100);
      console.log(
        `  ✓ ${entry.name.padEnd(70)} ${Math.round(inputSizeKB)}kb → ${Math.round(outputSizeKB)}kb  (${reduction}% smaller)`
      );

      total += inputSizeKB;
      saved += (inputSizeKB - outputSizeKB);
    } catch (err) {
      console.error(`  ✗ ${entry.name}: ${err.message}`);
    }
  }
}

console.log('Compressing clinic photos...\n');
await processDir(INPUT_BASE, OUTPUT_BASE);
console.log(`\nDone. Total: ${Math.round(total / 1024)}MB → saved ${Math.round(saved / 1024)}MB`);
console.log(`Output: ${OUTPUT_BASE}`);
console.log(`\nNext step: run scripts/upload-to-spaces.sh to push to DO Spaces`);
